name: Fly Deploy
on: 
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app to fly.io
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
          
        - name: Setup flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master
          
        - name: Download deployment config
          env:
            TOKEN: ${{ secrets.REPOCONFIGS_ACCESS_TOKEN }}
          run: |
            curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/CalemRoelofs/RepoConfigs/main/hnrtwpwa/fly.toml --output fly.toml
        
        - name: Deploy app to fly.io
          run: flyctl deploy --remote-only
